module.exports = {
	RECEIVE_GAME_ID: 'RECEIVE_GAME_ID',
	REQUEST_GAME_ID: 'REQUEST_GAME_ID',
	DISABLE_GAME: 'DISABLE_GAME',
	JOIN_GAME: 'JOIN_GAME',
	OPPONENT_LEFT: 'OPPONENT_LEFT',
	ALL_CLIENTS_CONNECTED: 'ALL_CLIENTS_CONNECTED',
	PLAYER_READY: 'PLAYER_READY',
	OPPONENT_READY: 'OPPONENT_READY',
	CAN_GUESS: 'CAN_GUESS',
	SEND_GUESS: 'SEND_GUESS',
	RECEIVE_GUESS: 'RECEIVE_GUESS',
	SEND_GUESS_FEEDBACK: 'SEND_GUESS_FEEDBACK',
	RECEIVE_GUESS_FEEDBACK: 'RECEIVE_GUESS_FEEDBACK',
	SEND_DESTROYED_SHIPS: 'SEND_DESTROYED_SHIPS',
	OPPONENT_SHIP_DESTROYED: 'OPPONENT_SHIP_DESTROYED',
	RECEIVE_DESTROYED_SHIP: 'RECEIVE_DESTROYED_SHIP' 
};