module.exports = {
	RECEIVE_GAME_ID: 'RECEIVE_GAME_ID',
	REQUEST_GAME_ID: 'REQUEST_GAME_ID',
	DISABLE_GAME: 'DISABLE_GAME',
	JOIN_GAME: 'JOIN_GAME',
	OPPONENT_LEFT: 'OPPONENT_LEFT',
	OPPONENT_JOINED: 'OPPONENT_JOINED'
};