export const PLACE_SHIP = 'PLACE_SHIP';
export const CAN_PLACE_SHIP = 'CAN_PLACE_SHIP';
export const UPDATE_BUSY_SQUARES = 'UPDATE_BUSY_SQUARES';
export const ADD_SHIPS = 'ADD_SHIPS';
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION';
export const SET_DRAG_ORIGIN = 'SET_DRAG_ORIGIN';
export const DISABLE_GAME = 'DISABLE_GAME';